id: sysprefs_time_server_configure
title: "Configure macOS to Use an Authorized Time Server"
discussion: |
  Approved time servers _MUST_ be the only servers configured for use.

  This rule ensures the uniformity of time stamps for information systems with multiple system clocks and systems connected over a network.
check: |
  /usr/bin/profiles -P -o stdout | /usr/bin/awk -F "= " '/timeServer/{print $2}' | /usr/bin/tr -d ';' | /usr/bin/tr -d '"'
result:
  string: "time-a.nist.gov,time-b.nist.gov"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-85448-9
  cci: 
    - CCI-001891
    - CCI-002046
  800-53r4: 
    - AU-8(1)
  srg: 
    - SRG-OS-000355-GPOS-00143
    - SRG-OS-000356-GPOS-00144
  disa_stig: 
    - AOSX-15-000014
  800-171r2:
    - 3.3.7
macOS:
  - "11.0"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_moderate
  - 800-53r4_high
  - STIG
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    timeServer: "time-a.nist.gov,time-b.nist.gov"