id: os_application_deny_list
title: "Apps not allowed on the device"
discussion: |
  In case specific apps are allowed to be used on the device a specific list _SHOULD_VALUEONDEMAND_ needs to be defined by the MDM. These apps will not open on the device.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-95650-8
  800-53r5:
    - N/A
  indigo:
    - ANNEX D (Section 5.8 - App-Installation)
    - ANNEX N
iOS:
  - "26.0"
tags:
  - ios
  - manual
  - indigo_base
  - indigo_high
supervised: true
mobileconfig: false # Set to true when implementing
mobileconfig_info:
  com.apple.applicationaccess:
    blockedAppBundleIDs: # Add bundle identifiers below
      - bundleID1
      - bundleID2
    
