id: os_application_deny_list
title: Apps not allowed on the device
discussion: |
  In case specific apps are allowed to be used on the device a specific list _SHOULD_VALUEONDEMAND_ needs to be defined by the MDM. These apps will not open on the device.
references:
  nist:
    cce:
      ios_18:
        - CCE-94517-0
      ios_17:
        - CCE-93471-1
  bsi:
    indigo:
      ios_17:
        - ANNEX D (Section 5.8 - App-Installation)
        - ANNEX N
platforms:
  iOS:
    '18.0':
      supervised: true
      benchmarks:
        - indigo_base
        - indigo_high
    '17.0':
      supervised: true
      benchmarks:
        - indigo_base
        - indigo_high
tags:
  - manual
mobileconfig_info:
  com.apple.applicationaccess:
    blockedAppBundleIDs:
      - bundleID1
      - bundleID2
