id: os_config_data_install_enforce
title: "Enforce Installation of XProtect, MRT, and Gatekeeper Updates Automatically"
discussion: |
  Software Update _MUST_ be configured to update XProtect, MRT, and Gatekeepr automatically.

  This setting enforces definition updates for XProtect, MRT, and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.
  
  link:https://support.apple.com/en-us/HT207005[]

  NOTE: Software update will automatically update XProtect, MRT, and Gatekeeper by default in the macOS.
check: |
  /usr/bin/profiles -P -o stdout | /usr/bin/grep -c 'ConfigDataInstall = 1'
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-84929-9
  800-53r5:
    - SI-3
    - SI-2(5)
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
macOS:
  - "10.15"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
mobileconfig: true
mobileconfig_info:
  com.apple.SoftwareUpdate:
    ConfigDataInstall: true
