id: os_directory_services_configured
title: Integrate System into a Directory Services Infrastructure
discussion: |
  The macOS system _MUST_ be integrated into a directory services infrastructure.

  A directory service infrastructure enables centralized user and rights management, as well as centralized control over computer and user configurations. Integrating the macOS systems used throughout an organization into a directory services infrastructure ensures more administrator oversight and security than allowing distinct user account databases to exist on each separate system.
references:
  nist:
    cce:
      macos_26:
        - CCE-95181-4
      macos_15:
        - CCE-94181-5
      macos_14:
        - CCE-92780-6
  cis:
    controls_v8:
      - 6.7
platforms:
  macOS:
    '26.0': {}
    '15.0': {}
    '14.0': {}
    enforcement_info:
      check:
        shell: /usr/bin/dscl localhost -list . | /usr/bin/grep -qvE '(Contact|Search|Local|^$)'; /bin/echo $?
        result:
          integer: 0
      fix:
        additional_info: Integrate the system into an existing directory services infrastructure.
tags:
  - cisv8
