id: os_directory_services_configured
title: "Integrate System into a Directory Services Infrastructure"
discussion: |
  The macOS system _MUST_ be integrated into a directory services infrastructure. 

  A directory service infrastructure enables centralized user and rights management, as well as centralized control over computer and user configurations. Integrating the macOS systems used throughout an organization into a directory services infrastructure ensures more administrator oversight and security than allowing distinct user account databases to exist on each separate system.
check: |
  /usr/bin/dscl localhost -list . | /usr/bin/grep -qvE '(Contact|Search|Local|^$)'; /bin/echo $?
result:
  integer: 0  
fix: |
  Integrate the system into an existing directory services infrastructure.
references:
  cce:
    - CCE-91087-7
  cci:
    - CCI-000366
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - SRG-OS-000480-GPOS-00227
  disa_stig:
    - APPL-12-000016
  cis:
    benchmark:
      - N/A
    controls v8:
      - 6.7
macOS:
  - "12.0"
tags:
  - cisv8
  - stig
severity: "high"
mobileconfig:
mobileconfig_info: