id: "os_erase_contents_and_settings_disable"
title: "Ensure Allow Erase All Content and Settings is set to Disabled"
discussion: |
  Erase all contents and settings _MUST_ be disabled on institutionally owned iOS devices.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - CM-6
    - CM-7
    - CM-7(1)
  sfr:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 3.2.1.12 (level 1 - Institutionally-Owned Devices)
    v8:
      - 4.1
ios:
  - "16.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
severity: ""
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowEraseContentAndSettings: false