id: os_install_configuration_profile_disable
title: "Ensure Allow Installing Configuration Profiles is Set to Disabled"
discussion: |
  Configuration profiles _MUST_ be installed via an organization's MDM.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  800-53r5:
    - CM-6
    - CM-7
    - CM-7(1)
visionOS:
  - '2.0'
tags:
  - visionos
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUIConfigurationProfileInstallation: false