id: os_install_log_retention_configure
title: Configure Install.log Retention to $ODV
discussion: |
  The install.log _MUST_ be configured to require records be kept for a organizational defined value before deletion, unless the system uses a central audit record storage facility.
references:
  nist:
    cce:
      macos_15:
        - CCE-94212-8
      macos_14:
        - CCE-92811-9
      macos_13:
        - CCE-91807-8
    800-53r5:
      - AU-11
      - AU-4
    800-171r3:
      - 03.03.03
  disa:
    cci:
      - CCI-001849
    srg:
      - SRG-OS-000341-GPOS-00132
    disa_stig:
      macos_15:
        - APPL-15-004050
      macos_14:
        - APPL-14-004050
    cmmc:
      - AU.L2-3.3.1
  cis:
    benchmark:
      macos_15:
        - 3.3 (level 1)
      macos_14:
        - 3.3 (level 1)
      macos_13:
        - 3.3 (level 1)
    controls_v8:
      - 8.1
      - 8.3
platforms:
  macOS:
    check: |
      /usr/sbin/aslmanager -dd 2>&1 | /usr/bin/awk '/\/var\/log\/install.log$/ {count++} /Processing module com.apple.install/,/Finished/ { for (i=1;i<=NR;i++) { if ($i == "TTL" && $(i+2) >= $ODV) { ttl="True" }; if ($i == "MAX") {max="True"}}} END{if (count > 1) { print "Multiple config files for /var/log/install, manually remove the extra files"} else if (max == "True") { print "all_max setting is configured, must be removed" } if (ttl != "True") { print "TTL not configured" } else { print "Yes" }}'
    result:
      string: 'Yes'
    fix: |
      [source,bash]
      ----
      /usr/bin/sed -i '' "s/\* file \/var\/log\/install.log.*/\* file \/var\/log\/install.log format='\$\(\(Time\)\(JZ\)\) \$Host \$\(Sender\)\[\$\(PID\\)\]: \$Message' rotate=utc compress file_max=50M size_only ttl=$ODV/g" /etc/asl/com.apple.install
      ----

      NOTE: If there are multiple configuration files in /etc/asl that are set to process the file /var/log/install.log, these files will have to be manually removed.
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
odv:
  hint: Number of days.
  recommended: 365
  cis_lvl1: 365
  cis_lvl2: 365
  stig: 365
tags:
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
