id: "os_modify_cellular_data_app_settings_disable"
title: "Ensure Allow modifying cellular data app settings is set to Disabled"
discussion: |
  The ability to modify cellular data app settings _MUST_ be disabled.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - CM-7
    - CM-7(1)
  sfr:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 3.2.1.18 (level 2 - Institutionally-Owned Devices)
    v8:
      - 4.1
iOS:
  - "16.0"
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl2_enterprise
  - cisv8
severity: ""
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowAppCellularDataModification: false