id: os_newsyslog_files_permissions_configure
title: Configure System Log Files to Mode 640 or Less Permissive
discussion: |
  The system logs _MUST_ be configured to be writable by root and readable only by the root user and group wheel. To achieve this, system log files _MUST_ be configured to mode 640 permissive or less; thereby preventing normal users from reading, modifying or deleting audit logs. System logs frequently contain sensitive information that could be used by an attacker. Setting the correct permissions mitigates this risk.
references:
  nist:
    cce:
      macos_15:
        - CCE-94234-2
      macos_14:
        - CCE-92830-9
      macos_13:
        - CCE-91826-8
      monterey:
        - CCE-90955-6
      big_sur:
        - CCE-85470-3
      catalina:
        - CCE-84934-9
    800-53r5:
      - SI-11
  disa:
    cci:
      - CCI-001312
      - CCI-001314
    srg:
      - SRG-OS-000206-GPOS-00084
      - SRG-OS-000205-GPOS-00083
    disa_stig:
      macos_15:
        - APPL-15-004040
      macos_14:
        - APPL-14-004040
      macos_13:
        - APPL-13-004002
      monterey:
        - APPL-12-004002
      big_sur:
        - APPL-11-004002
      catalina:
        - AOSX-15-004002
platforms:
  macOS:
    check: |
      /usr/bin/stat -f '%A:%N' $(/usr/bin/grep -v '^#' /etc/newsyslog.conf | /usr/bin/awk '{ print $1 }') 2> /dev/null | /usr/bin/awk '!/640/{print $1}' | /usr/bin/wc -l | /usr/bin/tr -d ' '
    result:
      integer: 0
    fix: |
      [source,bash]
      ----
      /bin/chmod 640 $(/usr/bin/stat -f '%A:%N' $(/usr/bin/grep -v '^#' /etc/newsyslog.conf | /usr/bin/awk '{ print $1 }') 2> /dev/null | /usr/bin/awk '!/640/{print $1}' | awk -F":" '!/640/{print $2}')
      ----
    '15.0':
      severity: medium
      benchmarks:
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - disa_stig
    '13.0':
      severity: medium
      benchmarks:
        - disa_stig
    monterey:
      severity: medium
      benchmarks:
        - disa_stig
    big_sur:
      severity: medium
      benchmarks:
        - disa_stig
    catalina:
      severity: medium
      benchmarks:
        - disa_stig
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - cnssi-1253_low
  - cnssi-1253_high
  - cnssi-1253_moderate
  - manual
