id: os_policy_banner_ssh_configure
title: "Display Policy Banner at Remote Login"
discussion: |
  Remote login service _MUST_ be configured to display a policy banner at login. 

  Displaying a standardized and approved use notification before granting access to the operating system ensures that users are provided with privacy and security notification verbiage that is consistent with applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance.

  System use notifications are required only for access via login interfaces with human users and are not required when such human interfaces do not exist.
check: |
  bannerText="You are accessing a U.S. Government information system, which includes: 1) this computer, 2) this computer network, 3) all Government-furnished computers connected to this network, and 4) all Government-furnished devices and storage media attached to this network or to a computer on this network. You understand and consent to the following: you may access this information system for authorized use only; unauthorized use of the system is prohibited and subject to criminal and civil penalties; you have no reasonable expectation of privacy regarding any communication or data transiting or stored on this information system at any time and for any lawful Government purpose, the Government may monitor, intercept, audit, and search and seize any communication or data transiting or stored on this information system; and any communications or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose. This information system may contain Controlled Unclassified Information (CUI) that is subject to safeguarding or dissemination controls in accordance with law, regulation, or Government-wide policy. Accessing and using this system indicates your understanding of this warning."
  /usr/bin/grep -c "$bannerText" /etc/banner
result:
  integer: 1
fix: |
  [source,bash]
  ----
  bannerText="You are accessing a U.S. Government information system, which includes: 1) this computer, 2) this computer network, 3) all Government-furnished computers connected to this network, and 4) all Government-furnished devices and storage media attached to this network or to a computer on this network. You understand and consent to the following: you may access this information system for authorized use only; unauthorized use of the system is prohibited and subject to criminal and civil penalties; you have no reasonable expectation of privacy regarding any communication or data transiting or stored on this information system at any time and for any lawful Government purpose, the Government may monitor, intercept, audit, and search and seize any communication or data transiting or stored on this information system; and any communications or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose. This information system may contain Controlled Unclassified Information (CUI) that is subject to safeguarding or dissemination controls in accordance with law, regulation, or Government-wide policy. Accessing and using this system indicates your understanding of this warning."
  /bin/echo "${bannerText}" > /etc/banner
  ----   
references:
  cce:
    - CCE-90974-7
  cci: 
    - CCI-000048
  800-53r5:
    - AC-8
  800-53r4: 
    - AC-8
  srg:
    - SRG-OS-000023-GPOS-00006
  disa_stig:
    - APPL-12-000023
  800-171r2:
    - 3.1.9
macOS:
  - "12.0"
tags:
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info: