id: os_system_settings_find_my_friends_modification_disable
title: Disable Find My Friends Modification
discussion: |
  The Find My service modification _MUST_ be disabled.
references:
  nist:
    cce:
      ios_18:
        - CCE-94556-8
      ios_17:
        - CCE-93504-9
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
  bsi:
    indigo:
      ios_17:
        - ANNEX K
platforms:
  iOS:
    '18.0':
      supervised: true
      benchmarks:
        - indigo_high
    '17.0':
      supervised: true
      benchmarks:
        - indigo_high
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
mobileconfig_info:
  com.apple.applicationaccess:
    allowFindMyFriendsModification: false
