id: os_ssh_client_alive_count_max_configure
title: "Set SSH Active Client Alive Maximum to Zero"
discussion: |
  SSH _MUST_ be configured with an Active Client Alive Maximum Count set to zero. Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session or an incomplete login attempt will also free up resources committed by the managed network element.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/grep -c "^ClientAliveCountMax 0" /etc/ssh/sshd_config
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/.*ClientAliveCountMax.*/ClientAliveCountMax 0/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
  ----
references:
  cce:
    - CCE-84792-1
  cci: 
    - CCI-001133
  800-53r4: 
    - SC-10
  srg: 
    - SRG-OS-000163-GPOS-00072
  disa_stig: 
    - AOSX-14-000052
  800-171r2:
    - 3.13.9
macOS:
  - "10.15"
tags:
  - 800-171
  - cnssi-1253
  - fisma-moderate
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info: