id: os_system_settings_find_my_friends_modification_disable
title: "Disable Find My Friends Modification"
discussion: |
  The Find My service modification _MUST_ be disabled.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  800-53r5:
    - AC-20
    - CM-7
    - CM-7(1)
  indigo:
    - ANNEX K
iOS:
  - "26.0"
tags:
  - ios
  - indigo_high
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high  
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowFindMyFriendsModification: false
