id: os_system_settings_find_my_device_disable
title: "Disable Find My Device"
discussion: |
  The Find My service _MUST_ be disabled.

  A Mobile Device Management (MDM) solution _MUST_ be used to carry out remote locking and wiping instead of Apple's Find My service.

  Apple's Find My service uses a personal AppleID for authentication. Organizations should rely on MDM solutions, which have much more secure authentication requirements, to perform remote lock and remote wipe.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-95533-6
  800-53r5:
    - AC-20
    - CM-7
    - CM-7(1)
  indigo:
    - ANNEX K
  cmmc:
    - AC.L1-B.1.III
    - AC.L2-3.1.20
    - CM.L2-3.4.6
    - CM.L2-3.4.7
iOS:
  - "26.0"
tags:
  - ios
  - indigo_high
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cmmc_lvl1
  - cmmc_lvl2
  - cmmc_lvl3
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowFindMyDevice: false
