id: os_sshd_permit_root_login_configure
title: "Disable Root Login for SSH"
discussion: |
  If SSH is enabled to assure individual accountability and prevent unauthorized access, logging in as root via SSH _MUST_ be disabled. 
  
  The macOS system MUST  require individuals to be authenticated with an individual authenticator prior to using a group authenticator, and administrator users _MUST_ never log in directly as root. 
  
  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/grep -c "^PermitRootLogin no" /etc/ssh/sshd_config
result:
  integer: 1
fix: |
  To ensure that "PermitRootLogin" is set disabled by sshd, run the following command: 
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/^[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
  ----
references:
  cce:
    - CCE-85385-3
  cci: 
    - CCI-000770
  800-53r4: 
    - IA-2(5)
  srg: 
    - SRG-OS-000109-GPOS-00056
  disa_stig: 
    - AOSX-15-001100
macOS:
  - "11.0"
tags:
  - STIG
mobileconfig: false
mobileconfig_info: