id: os_time_offset_limit_configure
title: Ensure Time Offset Within Limits
discussion: |
  The macOS system time  _MUST_ be monitored to not drift more than four minutes and thirty seconds.
references:
  nist:
    cce:
      macos_26:
        - CCE-95324-0
      macos_15:
        - CCE-94318-3
      macos_14:
        - CCE-92915-8
platforms:
  macOS:
    '26.0': {}
    '15.0': {}
    '14.0': {}
    enforcement_info:
      check:
        shell: /usr/bin/sntp $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}') | /usr/bin/awk -F'.' '/\+\/\-/{if (substr($1,2) >= 270) {print "No"} else {print "Yes"}}'
        result:
          string: 'Yes'
      fix:
        shell: /usr/bin/sntp -Ss $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}')
