---
ddm:
  supported_types:
    - com.apple.configuration.services.configuration-files
    - com.apple.configuration.passcode.settings
    - com.apple.configuration.diskmanagement.settings

  services:
    com.apple.bash: /etc/
    com.apple.pam: /etc/pam.d/
    com.apple.sshd: /etc/ssh/
    com.apple.sudo: /etc/
    com.apple.zsh: /etc/
    com.apple.cups: /etc/cups/

authors:
  - name: Bob Gendler
    organization: National Institute of Standards and Technology
    benchmarks:
    - mscp
  - name: Dan Brodjieski
    organization: National Aeronautics and Space Administration
    benchmarks:
    - mscp
  - name: Bob Gendler
    organization: Jamf
    benchmarks:
    - mscp
  - name: Edward Byrd
    organization: Center for Internet Security
    benchmarks:
    - cis_lvl1
    - cis_lvl2
    - cisv8
  - name: John Mahlman
    organization: Leidos
    benchmarks:
    - cmmc_lvl1
    - cmmc_lvl2
  - name: Rob Lamb
    organization: Los Alamos National Laboratory
    benchmarks:
    - cnssi-1253_low
    - cnssi-1253_moderate
    - cnssi-1253_high
  - name: Ekkehard Koch
    organization: ""
    benchmarks:
    - cnssi-1253_low
    - cnssi-1253_moderate
    - cnssi-1253_high
  - name: Aaron Kegerreis
    organization: Defense Information Systems Agency
    benchmarks:
    - disa_stig
  - name: Marco Pi√±eyro
    organization: Department of State
    benchmarks:
    - ios_stig
    - ios_byoad
  - name: Henry Stamerjohann
    organization: Declarative IT GmbH
    benchmarks:
    - indigo_base
    - indigo_high
  - name: Jordy Witteman
    organization: Root3
    benchmarks:
    - nlmapgov_base
    - nlmapgov_plus

versions:
  platforms:
    macos:
      - os_version: 26.0
        os_name: "tahoe"
        compliance_version: "Tahoe Guidance, Revision X.X"
        revision: 1.1
        cpe: o:apple:macos:26.0
        date: "2025-12-16"
      
      - os_version: 15.0
        os_name: "sequoia"
        compliance_version: "Sequoia Guidance, Revision 1.1"
        revision: 1.1
        cpe: o:apple:macos:15.0
        date: "2024-12-16"

      - os_version: 14.0
        os_name: "sonoma"
        compliance_version: "Sonoma Guidance, Revision 3.1"
        revision: 3.1
        cpe: o:apple:macos:14.0
        date: "2024-12-16"

      - os_version: 13.0
        os_name: "ventura"
        compliance_version: "Ventura Guidance, Revision 5.1"
        revision: 5.1
        cpe: o:apple:macos:13.0
        date: "2024-12-16"

    ios:
      - os_version: 26.0
        os_name: "ios_26"
        compliance_version: "iOS 26 Guidance, Revision X.X"
        revision: 1.0
        cpe: o:apple:ios:26.0
        date: "2025-12-16"
      - os_version: 18.0
        os_name: "ios_18"
        compliance_version: "iOS 18 Guidance, Revision 1.1"
        revision: 1.1
        cpe: o:apple:ios:18.0
        date: "2024-12-16"

      - os_version: 17.0
        os_name: "ios_17"
        compliance_version: "iOS 17 Guidance, Revision 3.0"
        revision: 3.0
        cpe: o:apple:ios:17.0
        date: "2024-09-12"

      - os_version: 16.0
        os_name: "ios_16"
        compliance_version: "iOS 16 Guidance, Revision 3.0"
        revision: 3.0
        cpe: o:apple:ios:16.0
        date: "2024-09-12"

    visionos:
      - os_version: 26.0
        os_name: "visionos_26"
        compliance_version: "visionOS 26.0 Guidance, Revision X.X"
        revision: 1.0
        cpe: o:apple:visionos:26.0
        date: "2025-09-12"
      - os_version: 2.0
        os_name: "visionos_2"
        compliance_version: "visionOS 2.0 Guidance, Revision 1.0"
        revision: 1.0
        cpe: o:apple:visionos:2.0
        date: "2024-09-12"
