id: settings_siri_disable
title: Disable Siri
discussion: |
  Support for Siri is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities.
references:
  nist:
    cce:
      visionos_2:
        - CCE-94512-1
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
      - SC-7(10)
platforms:
  visionOS:
    '2.0':
      supervised: false
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
mobileconfig_info:
  com.apple.applicationaccess:
    allowAssistant: false
