id: system_settings_wallet_applepay_prefpane_hide
title: Hide the System Preference Pane for Wallet and Apple Pay
discussion: |
  This is required for compliance with the DISA STIG for macOS.

  The domain *com.apple.systempreferences* has been deprecated by Apple in macOS 13. The recommended way to disable System Setting Panes is to use the *DisabledSystemSettings* key. Addtionally, hiding System Settings Preference Panes are not possible in macOS 13.

  link:https://developer.apple.com/documentation/devicemanagement/systempreferences[]
references:
  nist:
    cce:
      ventura:
        - CCE-92013-2
    800-53r5:
      - null
    800-171r3:
      - null
  disa:
    cci:
      - CCI-000381
      - CCI-001774
    srg:
      - SRG-OS-000095-GPOS-00049
      - SRG-OS-000370-GPOS-00155
    disa_stig:
      ventura:
        - APPL-13-002052
  cis:
    benchmark:
      ventura:
        - null
    controls_v8:
      - null
platforms:
  macOS:
    ventura:
      severity: medium
      benchmarks:
        - disa_stig
    check: |
      /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="HiddenPreferencePanes"]/following-sibling::*[1]' - | /usr/bin/grep -c com.apple.preferences.wallet
    result:
      integer: 1
tags: []
mobileconfig_info:
  com.apple.systempreferences:
    HiddenPreferencePanes:
      - com.apple.preferences.wallet
