id: system_settings_guest_access_smb_disable
title: Disable Guest Access to Shared SMB Folders
discussion: |
  Guest access to shared Server Message Block (SMB) folders _MUST_ be disabled.

  Turning off guest access prevents anonymous users from accessing files shared via SMB.
references:
  nist:
    cce:
      macos_15:
        - CCE-94366-2
      macos_14:
        - CCE-92963-8
      macos_13:
        - CCE-91952-2
    800-171r3:
      - 03.01.01
  disa:
    cmmc:
      - AC.L1-3.1.2
  cis:
    benchmark:
      macos_15:
        - 2.12.2 (level 1)
      macos_14:
        - 2.12.2 (level 1)
      macos_13:
        - 2.12.2 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    check: |
      /usr/bin/defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server AllowGuestAccess
    result:
      boolean: 0
    fix: |
      [source,bash]
      ----
      /usr/sbin/sysadminctl -smbGuestAccess off
      ----
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
