id: system_settings_cd_dvd_sharing_disable
title: Disable CD/DVD Sharing
discussion: |
  CD/DVD Sharing _MUST_ be disabled.
references:
  nist:
    cce:
      macos_13:
        - CCE-91942-3
    800-53r5:
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.04.06
  disa:
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_13:
        - 2.3.3.1 (level 1)
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    check: |
      /usr/bin/pgrep -q ODSAgent; /bin/echo $?
    result:
      integer: 1
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
