id: system_settings_content_caching_disable
title: "Disable Content Caching Service"
discussion: |
  Content caching _MUST_ be disabled.

  Content caching is a macOS service that helps reduce Internet data usage and speed up software installation on Mac computers. It is not recommended for devices furnished to employees to act as a caching server.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowContentCaching').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-92954-7
  cci:
    - N/A
  800-53r5:
    - CM-7
    - CM-7(1)
  800-53r4:
    - CM-7
    - CM-7(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.4.6
  cis:
    benchmark:
      - 2.3.3.9 (level 2)
    controls v8:
      - 4.8
  cmmc:
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowContentCaching: false