id: system_settings_screen_sharing_disable
title: Disable Screen Sharing and Apple Remote Desktop
discussion: |
  Support for both Screen Sharing and Apple Remote Desktop (ARD) is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling screen sharing and ARD helps prevent the unauthorized connection of devices, the unauthorized transfer of information, and unauthorized tunneling.
check: |
  result="FAIL"
  enabled=$(/bin/launchctl print-disabled system | /usr/bin/grep '"com.apple.screensharing" => enabled')
  running=$(/bin/launchctl print system/com.apple.screensharing 2>/dev/null)
  
  if [[ -z "$running" ]] && [[ -z "$enabled" ]]; then
    result="PASS"
  elif [[ -n "$running" ]]; then
    result=result+" RUNNING"
  elif [[ -n "$enabled" ]]; then
    result=result+" ENABLED"
  fi
  echo $result
result:
  string: PASS
fix: |
  [source,bash]
  ----
  /bin/launchctl bootout system/com.apple.screensharing
  /bin/launchctl disable system/com.apple.screensharing
  ----
  NOTE - This will apply to the whole system
references:
  cce:
    - CCE-95394-3
  cci:
    - CCI-000213
  800-53r5:
    - AC-3
    - AC-17
  800-53r4:
    - AC-3
    - AC-17
  srg:
    - SRG-OS-000080-GPOS-00048
  disa_stig:
    - APPL-26-002050
  800-171r3:
    - 03.01.02
    - 03.04.06
  cis:
    benchmark:
      - 2.3.3.1 (level 1)
    controls v8:
      - 4.1
      - 4.8
  cmmc:
    - AC.L1-3.1.1
macOS:
  - '26.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - stig
  - cnssi-1253_moderate
severity: medium
mobileconfig: false
mobileconfig_info:
