id: system_settings_siri_disable
title: "Disable Siri"
discussion: |
  Support for Siri is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowAssistant').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-92987-7
  cci:
    - CCI-000381
    - CCI-001774
  800-53r5:
    - AC-20
    - CM-7
    - CM-7(1)
    - SC-7(10)
  800-53r4:
    - CM-7
    - CM-7(1)
    - AC-20
  srg:
    - SRG-OS-000095-GPOS-00049
    - SRG-OS-000370-GPOS-00155
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.20
    - 3.4.6
  cis:
    benchmark:
      - N/A
    controls v8:
      - 4.1
      - 4.8
  cmmc:
    - AC.L1-3.1.20
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowAssistant: false