id: system_settings_touch_id_settings_disable
title: Disable the Touch ID System Settings Pane
discussion: |
  The System Settings pane for Touch ID _MUST_ be disabled.

  Disabling the System Settings pane prevents the users from configuring Touch ID.
references:
  nist:
    cce:
      macos_26:
        - CCE-95414-9
      macos_15:
        - CCE-94407-4
      macos_14:
        - CCE-93020-6
    800-53r5:
      - CM-7
      - CM-7(1)
      - CM-7(5)
    800-171r3:
      - 03.04.06
      - 03.04.08
  disa:
    disa_stig:
      macos_14:
        - APPL-14-002051
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    '26.0': {}
    '15.0': {}
    '14.0':
      benchmarks:
        - name: disa_stig
          severity: medium
    enforcement_info:
      check:
        shell: /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledSystemSettings"]/following-sibling::*[1]' - | /usr/bin/grep -c "com.apple.Touch-ID-Settings.extension"
        result:
          integer: 1
    introduced: '13.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cmmc_lvl2
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
mobileconfig_info:
  - PayloadType: com.apple.systempreferences
    PayloadContent:
      - DisabledSystemSettings:
          - com.apple.Touch-ID-Settings.extension
