id: system_settings_personalized_advertising_disable
title: Disable Personalized Advertising
discussion: |
  Ad tracking and targeted ads _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling ad tracking ensures that applications and advertisers are unable to track users' interests and deliver targeted advertisements.
references:
  nist:
    cce:
      macos_15:
        - CCE-94383-7
      macos_14:
        - CCE-92979-4
      macos_13:
        - CCE-91968-8
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
      - SC-7(10)
    800-171r3:
      - 03.01.20
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      macos_15:
        - APPL-15-002200
      macos_14:
        - APPL-14-002200
    cmmc:
      - AC.L1-3.1.20
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_15:
        - 2.6.4 (level 1)
      macos_14:
        - 2.6.4 (level 1)
      macos_13:
        - 2.6.3 (level 1)
    controls_v8:
      - 4.8
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
      .objectForKey('allowApplePersonalizedAdvertising').js
      EOS
    result:
      string: 'false'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.applicationaccess:
    allowApplePersonalizedAdvertising: false
