id: system_settings_time_server_enforce
title: Enforce macOS Time Synchronization
discussion: |
  Time synchronization _MUST_ be enforced on all networked systems.

  This rule ensures the uniformity of time stamps for information systems with multiple system clocks and systems connected over a network.
references:
  nist:
    cce:
      sequoia:
        - CCE-94405-8
      sonoma:
        - CCE-93000-8
      ventura:
        - CCE-91990-2
    800-53r5:
      - AU-12(1)
      - SC-45(1)
    800-171r3:
      - 3.3.7
  disa:
    cci:
      - CCI-001891
      - CCI-002046
      - CCI-004923
      - CCI-004926
      - CCI-004922
    srg:
      - SRG-OS-000355-GPOS-00143
      - SRG-OS-000356-GPOS-00144
    disa_stig:
      sequoia:
        - APPL-15-000014
      sonoma:
        - APPL-14-000014
      ventura:
        - null
    cmmc:
      - AU.L2-3.3.7
  cis:
    benchmark:
      sequoia:
        - 2.3.2.1 (level 1)
      sonoma:
        - 2.3.2.1 (level 1)
      ventura:
        - 2.3.2.2 (level 1)
    controls_v8:
      - 8.4
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.timed')\
      .objectForKey('TMAutomaticTimeOnlyEnabled').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    sequoia:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    sonoma:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    ventura:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
tags:
  - 800-171
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.ManagedClient.preferences:
    com.apple.timed:
      TMAutomaticTimeOnlyEnabled: true
