id: system_settings_automatic_login_disable
title: "Disable Unattended or Automatic Logon to the System"
discussion: |
  Automatic logon _MUST_ be disabled.

  When automatic logons are enabled, the default user account is automatically logged on at boot time without prompting the user for a password. Even if the screen is later locked, a malicious user would be able to reboot the computer and find it already logged in. Disabling automatic logons mitigates this risk.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
  .objectForKey('com.apple.login.mcx.DisableAutoLoginClient').js
  EOS
result:
  string: "true"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-92947-1
  cci:
    - CCI-000366
  800-53r5:
    - IA-2
    - IA-5(13)
  800-53r4:
    - IA-2
    - IA-5(13)
  srg:
    - SRG-OS-000480-GPOS-00229
  disa_stig:
    - N/A
  800-171r2:
    - 3.5.1
    - 3.5.2
  cis:
    benchmark:
      - 2.12.3 (level 1)
    controls v8:
      - 4.7
  cmmc:
    - IA.L1-3.5.1
    - IA.L1-3.5.2
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.loginwindow:
    com.apple.login.mcx.DisableAutoLoginClient: true
