id: system_settings_guest_account_disable
title: Disable the Guest Account
discussion: |
  Guest access _MUST_ be disabled.

  Turning off guest access prevents anonymous users from accessing files.
references:
  nist:
    cce:
      macos_15:
        - CCE-94367-0
      macos_14:
        - CCE-92964-6
      macos_13:
        - CCE-91953-0
    800-53r5:
      - AC-2
      - AC-2(9)
    800-171r3:
      - 03.01.01
  disa:
    cci:
      - CCI-001813
    srg:
      - SRG-OS-000364-GPOS-00151
      - SRG-OS-000480-GPOS-00228
    disa_stig:
      macos_15:
        - APPL-15-002063
      macos_14:
        - APPL-14-002063
      macos_13:
        - APPL-13-002063
    cmmc:
      - AC.L1-3.1.2
  cis:
    benchmark:
      macos_15:
        - 2.13.1 (level 1)
      macos_14:
        - 2.12.1 (level 1)
      macos_13:
        - 2.12.1 (level 1)
    controls_v8:
      - 5.2
      - 6.2
      - 6.8
platforms:
  macOS:
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '13.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: high
    enforcement_info:
      check:
        shell: |-
          /usr/bin/osascript -l JavaScript << EOS
          function run() {
            let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
          .objectForKey('DisableGuestAccount'))
            let pref2 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
          .objectForKey('EnableGuestAccount'))
            if ( pref1 == true && pref2 == false ) {
              return("true")
            } else {
              return("false")
            }
          }
          EOS
        result:
          string: 'true'
    introduced: '-1'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info:
  - PayloadType: com.apple.MCX
    PayloadContent:
      - DisableGuestAccount: true
      - EnableGuestAccount: false
