id: system_settings_hot_corners_disable
title: Disable Hot Corners
discussion: |
  Hot corners _MUST_ be disabled.

  The information system conceals, via the session lock, information previously visible on the display with a publicly viewable image. Although hot comers can be used to initiate a session lock or to launch useful applications, they can also be configured to disable an automatic session lock from initiating. Such a configuration introduces the risk that a user might forget to manually lock the screen before stepping away from the computer.
references:
  nist:
    cce:
      macos_26:
        - CCE-95375-2
      macos_15:
        - CCE-94368-8
      macos_14:
        - CCE-92965-3
    800-53r5:
      - AC-11(1)
    800-171r3:
      - 03.01.10
  disa:
    cci:
      - CCI-000060
    srg:
      - SRG-OS-000031-GPOS-00012
    disa_stig:
      macos_26:
        - APPL-26-000007
      macos_15:
        - APPL-15-000007
      macos_14:
        - APPL-14-000007
    cmmc:
      - AC.L2-3.1.10
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: disa_stig
          severity: medium
    '15.0':
      benchmarks:
        - name: disa_stig
          severity: medium
    '14.0':
      benchmarks:
        - name: disa_stig
          severity: medium
    enforcement_info:
      check:
        shell: /usr/bin/profiles -P -o stdout | /usr/bin/grep -Ec '"wvous-bl-corner" = 0|"wvous-br-corner" = 0|"wvous-tl-corner" = 0|"wvous-tr-corner" = 0'
        result:
          integer: 4
    introduced: '-1'
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
mobileconfig_info:
  - PayloadType: com.apple.ManagedClient.preferences
    PayloadContent:
      - com.apple.dock:
          wvous-bl-corner: 0
          wvous-br-corner: 0
          wvous-tr-corner: 0
          wvous-tl-corner: 0
