id: system_settings_improve_siri_dictation_disable
title: Disable Improve Siri and Dictation Information to Apple
discussion: |
  The ability for Apple to store and review audio of your Siri and Dictation interactions _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling the submission of Siri and Dictation information will mitigate the risk of unwanted data being sent to Apple.
references:
  nist:
    cce:
      sequoia:
        - CCE-94372-0
      sonoma:
        - CCE-92967-9
      ventura:
        - CCE-91956-3
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
      - SC-7(10)
    800-171r3:
      - 03.01.20
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      sequoia:
        - APPL-15-002210
      ventura:
        - APPL-13-002021
    cmmc:
      - AC.L1-3.1.20
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      sequoia:
        - 2.6.3.2 (level 1)
      sonoma:
        - 2.6.3 (level 2)
      ventura:
        - null
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.assistant.support')\
      .objectForKey('Siri Data Sharing Opt-In Status').js
      EOS
    result:
      integer: 2
    fix: |
      This is implemented by a Configuration Profile.
    sequoia:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    sonoma:
      severity: medium
      benchmarks:
        - cis_lvl2
        - disa_stig
    ventura:
      benchmarks:
        - disa_stig
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.assistant.support:
    Siri Data Sharing Opt-In Status: 2
