id: system_settings_printer_sharing_disable
title: Disable Printer Sharing
discussion: |
  Printer Sharing _MUST_ be disabled.
references:
  nist:
    cce:
      sequoia:
        - CCE-94384-5
      sonoma:
        - CCE-92980-2
      ventura:
        - CCE-91969-6
    800-53r5:
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      sequoia:
        - APPL-15-002240
      sonoma:
        - APPL-14-002240
      ventura:
        - null
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      sequoia:
        - 2.3.3.4 (level 1)
      sonoma:
        - 2.3.3.4 (level 1)
      ventura:
        - 2.3.3.4 (level 1)
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: |
      /usr/sbin/cupsctl | /usr/bin/grep -c "_share_printers=0"
    result:
      boolean: 1
    fix: |
      [source,bash]
      ----
      /usr/sbin/cupsctl --no-share-printers
      /usr/bin/lpstat -p | awk '{print $2}'| /usr/bin/xargs -I{} lpadmin -p {} -o printer-is-shared=false
      ----
    sequoia:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    sonoma:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    ventura:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
