id: system_settings_bluetooth_sharing_disable
title: Disable Bluetooth Sharing
discussion: |
  Bluetooth Sharing _MUST_ be disabled.

  Bluetooth Sharing allows users to wirelessly transmit files between the macOS and Bluetooth-enabled devices, including personally owned cellphones and tablets. A malicious user might introduce viruses or malware onto the system or extract sensitive files via Bluetooth Sharing. When Bluetooth Sharing is disabled, this risk is mitigated.

  [NOTE]
  ====
  The check and fix are for the currently logged in user. To get the currently logged in user, run the following.
  [source,bash]
  ----
  CURRENT_USER=$( /usr/sbin/scutil <<< "show State:/Users/ConsoleUser" | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }' )
  ----
  ====
references:
  nist:
    cce:
      macos_15:
        - CCE-94355-5
      macos_14:
        - CCE-92952-1
      macos_13:
        - CCE-91940-7
    800-53r5:
      - AC-3
      - AC-18(4)
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.04.06
  disa:
    cci:
      - CCI-000213
      - CCI-000381
    srg:
      - SRG-OS-000080-GPOS-00048
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      macos_15:
        - APPL-15-002110
      macos_14:
        - APPL-14-002110
    cmmc:
      - AC.L1-3.1.1
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_15:
        - 2.3.3.11 (level 1)
      macos_14:
        - 2.3.3.11 (level 1)
      macos_13:
        - 2.3.3.11 (level 1)
    controls_v8:
      - 3.3
      - 4.1
platforms:
  macOS:
    check: |
      /usr/bin/sudo -u "$CURRENT_USER" /usr/bin/defaults -currentHost read com.apple.Bluetooth PrefKeyServicesEnabled
    result:
      boolean: 0
    fix: |
      [source,bash]
      ----
      /usr/bin/sudo -u "$CURRENT_USER" /usr/bin/defaults -currentHost write com.apple.Bluetooth PrefKeyServicesEnabled -bool false
      ----
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
