id: system_settings_automatic_logout_enforce
title: Enforce Auto Logout After $ODV Seconds of Inactivity
discussion: |
  Auto logout _MUST_ be configured to automatically terminate a user session and log out the after $ODV seconds of inactivity.

  NOTE:The maximum that macOS can be configured for autologoff is $ODV seconds.

  [IMPORTANT]
  ====
  The automatic logout may cause disruptions to an organization's workflow and/or loss of data. Information System Security Officers (ISSOs) are advised to first fully weigh the potential risks posed to their organization before opting to disable the automatic logout setting.
  ====
references:
  nist:
    cce:
      sequoia:
        - CCE-94351-4
      sonoma:
        - CCE-92948-9
      ventura:
        - CCE-91935-7
    800-53r5:
      - AC-12
      - AC-2(5)
    800-171r3:
      - 03.01.01
      - 03.01.11
  disa:
    cci:
      - CCI-002361
    srg:
      - SRG-OS-000279-GPOS-00109
    disa_stig:
      sequoia:
        - APPL-15-000160
      sonoma:
        - APPL-14-000160
      ventura:
        - null
    cmmc:
      - AC.L2-3.1.10
      - AC.L2-3.1.11
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('.GlobalPreferences')\
      .objectForKey('com.apple.autologout.AutoLogOutDelay').js
      EOS
    result:
      integer: $ODV
    fix: |
      This is implemented by a Configuration Profile.
    sequoia:
      severity: medium
      benchmarks:
        - disa_stig
    sonoma:
      severity: medium
      benchmarks:
        - disa_stig
    ventura: {}
odv:
  hint: Number of seconds
  recommended: 86400
  stig: 86400
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
mobileconfig_info:
  .GlobalPreferences:
    com.apple.autologout.AutoLogOutDelay: $ODV
