id: system_settings_media_sharing_disabled
title: Disable Media Sharing
discussion: |
  Media sharing _MUST_ be disabled.

  When Media Sharing is enabled, the computer starts a network listening service that shares the contents of the user's music collection with other users in the same subnet.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling Media Sharing helps prevent the unauthorized connection of devices and the unauthorized transfer of information. Disabling Media Sharing mitigates this risk.

  NOTE: The Media Sharing preference panel will still allow "Home Sharing" and "Share media with guests" to be checked but the service will not be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowMediaSharing').js
  EOS
result:
  string: 'false'
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci:
    - CCI-000213
  800-53r5:
    - AC-3
    - AC-17
  800-53r4:
    - AC-3
  srg:
    - SRG-OS-000080-GPOS-00048
  disa_stig:
    - N/A
  800-171r3:
    - 03.01.02
    - 03.04.06
  cis:
    benchmark:
      - 2.3.3.10 (level 2)
    controls v8:
      - 4.1
      - 4.8
  cmmc:
    - AC.L1-3.1.1
macOS:
  - '15.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - stig
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowMediaSharing: false
