id: system_settings_bluetooth_sharing_disable
title: "Disable Bluetooth Sharing"
discussion: |
  Bluetooth Sharing _MUST_ be disabled.

  Bluetooth Sharing allows users to wirelessly transmit files between the macOS and Bluetooth-enabled devices, including personally owned cellphones and tablets. A malicious user might introduce viruses or malware onto the system or extract sensitive files via Bluetooth Sharing. When Bluetooth Sharing is disabled, this risk is mitigated.

  [NOTE]
  ====
  The check and fix are for the currently logged in user. To get the currently logged in user, run the following.
  [source,bash]
  ----
  CURRENT_USER=$( /usr/sbin/scutil <<< "show State:/Users/ConsoleUser" | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }' )
  ----
  ====
check: |
  /usr/bin/sudo -u "$CURRENT_USER" /usr/bin/defaults -currentHost read com.apple.Bluetooth PrefKeyServicesEnabled
result:
  boolean: 0
fix: |
  [source,bash]
  ----
  /usr/bin/sudo -u "$CURRENT_USER" /usr/bin/defaults -currentHost write com.apple.Bluetooth PrefKeyServicesEnabled -bool false
  ----
references:
  cce:
    - CCE-92952-1
  cci:
    - N/A
  800-53r5:
    - AC-3
    - AC-18(4)
    - CM-7
    - CM-7(1)
  800-53r4:
    - AC-3
    - AC-18(4)
    - CM-7
    - CM-7(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.1
    - 3.1.2
    - 3.1.16
    - 3.4.7
  cis:
    benchmark:
      - 2.3.3.11 (level 1)
    controls v8:
      - 3.3
      - 4.1
  cmmc:
    - AC.L1-3.1.1
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
mobileconfig: false
mobileconfig_info:

