id: system_settings_time_machine_encrypted_configure
title: Ensure Time Machine Volumes are Encrypted
discussion: |
  Time Machine volumes _MUST_ be encrypted.
references:
  nist:
    cce:
      sequoia:
        - CCE-94403-3
      sonoma:
        - CCE-92998-4
      ventura:
        - CCE-91988-6
    800-53r5:
      - null
    800-171r3:
      - null
  disa:
    cci:
      - null
    srg:
      - null
    disa_stig:
      sequoia:
        - null
      sonoma:
        - null
      ventura:
        - null
  cis:
    benchmark:
      sequoia:
        - 2.3.4.2 (level 1)
      sonoma:
        - 2.3.4.2 (level 1)
      ventura:
        - 2.3.4.2 (level 1)
    controls_v8:
      - 3.6
      - 3.11
      - 11.3
platforms:
  macOS:
    check: |
      error_count=0
      for tm in $(/usr/bin/tmutil destinationinfo 2>/dev/null| /usr/bin/awk -F': ' '/Name/{print $2}'); do
        tmMounted=$(/usr/sbin/diskutil info "${tm}" 2>/dev/null | /usr/bin/awk '/Mounted/{print $2}')
        tmEncrypted=$(/usr/sbin/diskutil info "${tm}" 2>/dev/null | /usr/bin/awk '/FileVault/{print $2}')
        if [[ "$tmMounted" = "Yes" && "$tmEncrypted" = "No" ]]; then
            ((error_count++))
        fi
      done
      echo "$error_count"
    result:
      integer: 0
    fix: |
      . Go to System Settings -> Time Machine
      . Click *Select Disk*
      . Select existing Backup Disk under *Available Disks*
      . Click *Encrypt Backups*
      . Click *Use Disk*
    sequoia:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    sonoma:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    ventura:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
