id: system_settings_guest_access_smb_disable
title: "Disable Guest Access to Shared SMB Folders"
discussion: |
  Guest access to shared Server Message Block (SMB) folders _MUST_ be disabled. 
  
  Turning off guest access prevents anonymous users from accessing files shared via SMB.
check: |
  /usr/bin/defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server AllowGuestAccess
result:
  boolean: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/sysadminctl -smbGuestAccess off
  ----
references:
  cce:
    - CCE-91952-2
  cci: 
    - N/A    
  800-171r2:
    - 3.5.1
    - 3.5.2
  800-53r5:
    - AC-2(9)
    - AC-2
  800-53r4:
    - AC-2
    - AC-2(9)
  disa_stig:
    - N/A
  srg:
    - N/A
  cis:
    benchmark: 
      - 2.12.2 (level 1)
    controls v8: 
      - 5.2
      - 6.2
      - 6.8
macOS:
  - "13.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: