id: system_settings_personalized_advertising_disable
title: "Disable Personalized Advertising"
discussion: |
  Ad tracking and targeted ads _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling ad tracking ensures that applications and advertisers are unable to track users' interests and deliver targeted advertisements.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowApplePersonalizedAdvertising').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-92979-4
  cci:
    - N/A
  800-53r5:
    - AC-20
    - CM-7
    - CM-7(1)
    - SC-7(10)
  800-53r4:
    - AC-20
    - CM-7
    - CM-7(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.20
    - 3.4.6
  cis:
    benchmark:
      - 2.6.4 (level 1)
    controls v8:
      - 4.8
  cmmc:
    - AC.L1-3.1.20
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowApplePersonalizedAdvertising: false