id: system_settings_remote_management_disable
title: Disable Remote Management
discussion: |
  Remote Management _MUST_ be disabled.
check: |
  /usr/libexec/mdmclient QuerySecurityInfo | /usr/bin/grep -c "RemoteDesktopEnabled = 0"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop
  ----
references:
  cce:
    - CCE-92982-8
  cci:
    - CCI-000381
  800-53r5:
    - AC-3
    - AC-17
    - CM-7
    - CM-7(1)
  800-53r4:
    - CM-7
    - CM-7(1)
  srg:
    - SRG-OS-000095-GPOS-00049
  disa_stig:
    - APPL-14-002250
  800-171r3:
    - 03.01.02
    - 03.04.06
  cis:
    benchmark:
      - 2.3.3.6 (level 1)
    controls v8:
      - 4.1
      - 4.8
      - 5.4
  cmmc:
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - '14.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - stig
severity: medium
mobileconfig: false
mobileconfig_info:
