id: system_settings_siri_prefpane_disable
title: "Disable the System Preference Pane for Siri"
discussion: |
  The system preference pane for Siri _MUST_ be disabled.

  Disabling the system preference pane prevents the users from configuring Siri. This will also hide the Siri System Setting.
check: |
  /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath 'string(//*[contains(text(), "DisabledPreferencePanes")]/following-sibling::*[1])' - | /usr/bin/grep -c com.apple.preference.speech
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91977-9
  cci: 
    - CCI-001774
    - CCI-000381
  800-53r5:
    - CM-7
    - CM-7(5)
  800-53r4: 
    - CM-7
    - CM-7(5)
  srg: 
    - SRG-OS-000095-GPOS-00049
  disa_stig: 
    - APPL-12-002053
  800-171r2:
    - N/A
  cmmc:
    - CM.L2-3.4.6
    - CM.L2-3.4.8
macOS:
  - "13.0"
tags:
  - stig
  - cmmc_lvl2
  - cmmc_lvl3
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledPreferencePanes: 
      - com.apple.preference.speech
