id: system_settings_internet_sharing_disable
title: Disable Internet Sharing
discussion: |
  If the system does not require Internet sharing, support for it is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling Internet sharing helps prevent the unauthorized connection of devices, unauthorized transfer of information, and unauthorized tunneling.
check: |

  if [ -n "${CACHED_PROFILES_FILE:-}" ] && [ -f "${CACHED_PROFILES_FILE}" ]; then
    /usr/bin/grep -qE 'forceInternetSharingOff = 1' "${CACHED_PROFILES_FILE}" && echo 1 || echo 0
  else
    /usr/bin/sudo /usr/bin/profiles -P -o stdout | /usr/bin/grep -qE 'forceInternetSharingOff = 1' && echo 1 || echo 0
  fi
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-94375-3
  cci:
    - CCI-000381
  800-53r5:
    - AC-4
    - AC-20
  800-53r4:
    - AC-4
    - AC-20
  srg:
    - SRG-OS-000095-GPOS-00049
  disa_stig:
    - APPL-15-002007
  800-171r3:
    - 03.01.03
    - 03.01.20
  cis:
    benchmark:
      - 2.3.3.7 (level 1)
    controls v8:
      - 4.1
      - 4.8
  cmmc:
    - AC.L1-3.1.20
    - AC.L2-3.1.3
macOS:
  - '15.0'
tags:
  - 800-53r5_low
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - stig
  - cnssi-1253_moderate
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    forceInternetSharingOff: true
