id: system_settings_media_sharing_disabled
title: Disable Media Sharing
discussion: |
  Media sharing _MUST_ be disabled.

  When Media Sharing is enabled, the computer starts a network listening service that shares the contents of the user's music collection with other users in the same subnet.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling Media Sharing helps prevent the unauthorized connection of devices and the unauthorized transfer of information. Disabling Media Sharing mitigates this risk.
references:
  nist:
    cce:
      macos_15:
        - CCE-94381-1
      macos_14:
        - CCE-92977-8
      macos_13:
        - CCE-91966-2
    800-53r5:
      - AC-3
      - AC-17
    800-171r3:
      - 03.01.02
      - 03.04.06
  disa:
    cci:
      - CCI-000213
    srg:
      - SRG-OS-000080-GPOS-00048
    disa_stig:
      macos_15:
        - APPL-15-002100
      macos_14:
        - APPL-14-002100
    cmmc:
      - AC.L1-3.1.1
  cis:
    benchmark:
      macos_15:
        - 2.3.3.10 (level 2)
      macos_14:
        - 2.3.3.10 (level 2)
      macos_13:
        - 2.3.3.10 (level 2)
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: $OS_VALUE
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl2
        - disa_stig
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        function run() {
          let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
        .objectForKey('allowMediaSharing'))
          let pref2 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
        .objectForKey('allowMediaSharingModification'))
          if ( pref1 == false && pref2 == false ) {
            return("true")
          } else {
            return("false")
          }
        }
        EOS
      mobileconfig_info:
        com.apple.applicationaccess:
          allowMediaSharing: false
          allowMediaSharingModification: false
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl2
        - disa_stig
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        function run() {
          let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('homeSharingUIStatus'))
          let pref2 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('legacySharingUIStatus'))
          let pref3 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('mediaSharingUIStatus'))
          if ( pref1 == 0 && pref2 == 0 && pref3 == 0 ) {
            return("true")
          } else {
            return("false")
          }
        }
        EOS
      mobileconfig_info:
        com.apple.preferences.sharing.SharingPrefsExtension:
          homeSharingUIStatus: 0
          legacySharingUIStatus: 0
          mediaSharingUIStatus: 0
    '13.0':
      benchmarks:
        - cis_lvl2
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        function run() {
          let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('homeSharingUIStatus'))
          let pref2 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('legacySharingUIStatus'))
          let pref3 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.preferences.sharing.SharingPrefsExtension')\
          .objectForKey('mediaSharingUIStatus'))
          if ( pref1 == 0 && pref2 == 0 && pref3 == 0 ) {
            return("true")
          } else {
            return("false")
          }
        }
        EOS
      mobileconfig_info:
        com.apple.preferences.sharing.SharingPrefsExtension:
          homeSharingUIStatus: 0
          legacySharingUIStatus: 0
          mediaSharingUIStatus: 0
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info: $OS_VALUE
