id: system_settings_wifi_disable_when_connected_to_ethernet
title: "Disable Wi-Fi When Connected to Ethernet"
discussion: |
  The macOS should be configured to automatically disable Wi-Fi when connected to ethernet.

  The use of Wi-Fi to connect to unauthorized networks may facilitate the exfiltration of mission data. Therefore, wireless networking capabilities internally embedded within information system components should be disabled when not intended to be used.

  NOTE: If the system requires Wi-Fi to connect to an authorized network, this is not applicable.
check: |
  The technology does not support this requirement. This is an applicable-does not meet finding.
fix: |
  This requirement is a permanent finding and cannot be fixed. An appropriate mitigation for the system must be implemented, but this finding cannot be considered fixed.
references:
  cce:
    - CCE-93009-9
  cci:
    - N/A
  800-53r5:
    - AC-4
    - AC-18(1)
    - AC-18(3)
  800-53r4:
    - AC-4
    - AC-18(1)
    - AC-18(3)
  disa_stig:
    - N/A
  srg:
    - N/A
  800-171r2:
    - 3.1.3
    - 3.1.17
  cmmc:
    - AC.L2-3.1.3
    - AC.L2-3.1.17
macOS:
  - "14.0"
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - permanent
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
mobileconfig: false
mobileconfig_info: