id: system_settings_remote_management_disable
title: Disable Remote Management
discussion: |
  Remote Management _MUST_ be disabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94386-0
      macos_14:
        - CCE-92982-8
      macos_13:
        - CCE-91971-2
    800-53r5:
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.01.02
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      macos_15:
        - APPL-15-002250
      macos_14:
        - APPL-14-002250
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_15:
        - 2.3.3.6 (level 1)
      macos_14:
        - 2.3.3.6 (level 1)
      macos_13:
        - 2.3.3.6 (level 1)
    controls_v8:
      - 4.1
      - 4.8
      - 5.4
platforms:
  macOS:
    check: |
      /usr/libexec/mdmclient QuerySecurityInfo | /usr/bin/grep -c "RemoteDesktopEnabled = 0"
    result:
      integer: 1
    fix: |
      [source,bash]
      ----
      /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop
      ----
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
