id: system_settings_screen_sharing_disable
title: Disable Screen Sharing and Apple Remote Desktop
discussion: |
  Support for both Screen Sharing and Apple Remote Desktop (ARD) is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling screen sharing and ARD helps prevent the unauthorized connection of devices, the unauthorized transfer of information, and unauthorized tunneling.
references:
  nist:
    cce:
      macos_15:
        - CCE-94387-8
      macos_14:
        - CCE-92983-6
      macos_13:
        - CCE-91972-0
    800-53r5:
      - AC-3
      - AC-17
    800-171r3:
      - 03.01.02
      - 03.04.06
  disa:
    cci:
      - CCI-000213
    srg:
      - SRG-OS-000080-GPOS-00048
    disa_stig:
      macos_15:
        - APPL-15-002050
      macos_14:
        - APPL-14-002050
      macos_13:
        - APPL-13-002050
    cmmc:
      - AC.L1-3.1.1
  cis:
    benchmark:
      macos_15:
        - 2.3.3.2 (level 1)
      macos_14:
        - 2.3.3.2 (level 1)
      macos_13:
        - 2.3.3.2 (level 1)
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: |
      /bin/launchctl print-disabled system | /usr/bin/grep -c '"com.apple.screensharing" => disabled'
    result:
      integer: 1
    fix: |
      [source,bash]
      ----
      /bin/launchctl disable system/com.apple.screensharing
      ----
      NOTE - This will apply to the whole system
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
