id: system_settings_printer_sharing_disable
title: Disable Printer Sharing
discussion: |
  Printer Sharing _MUST_ be disabled.
check: |
  /usr/sbin/cupsctl | /usr/bin/grep -c "_share_printers=0"
result:
  boolean: 1
fix: |
  [source,bash]
  ----
  /usr/sbin/cupsctl --no-share-printers
  /usr/bin/lpstat -p | awk '{print $2}'| /usr/bin/xargs -I{} lpadmin -p {} -o printer-is-shared=false
  ----
references:
  cce:
    - CCE-92980-2
  cci:
    - CCI-000381
  800-53r5:
    - CM-7
    - CM-7(1)
  800-53r4:
    - CM-7
    - CM-7(1)
  srg:
    - SRG-OS-000095-GPOS-00049
  disa_stig:
    - APPL-14-002240
  800-171r3:
    - 03.04.06
  cis:
    benchmark:
      - 2.3.3.4 (level 1)
    controls v8:
      - 4.1
      - 4.8
  cmmc:
    - CM.L2-3.4.6
    - CM.L2-3.4.7
macOS:
  - '14.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - stig
severity: medium
mobileconfig: false
mobileconfig_info:
