id: system_settings_bluetooth_menu_enable
title: Enable Bluetooth Menu
discussion: |
  The bluetooth menu _MUST_ be enabled.
references:
  nist:
    cce:
      sequoia:
        - CCE-94353-0
      sonoma:
        - CCE-92950-5
      ventura:
        - CCE-91937-3
    800-53r5:
      - null
    800-171r3:
      - null
  disa:
    cci:
      - null
    srg:
      - null
    disa_stig:
      sequoia:
        - null
      sonoma:
        - null
      ventura:
        - null
  cis:
    benchmark:
      sequoia:
        - 2.4.2 (level 1)
      sonoma:
        - 2.4.2 (level 1)
      ventura:
        - 2.4.2 (level 1)
    controls_v8:
      - 4.8
      - 13.9
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
      .objectForKey('Bluetooth').js
      EOS
    result:
      integer: 18
    fix: |
      This is implemented by a Configuration Profile.
    sequoia:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    sonoma:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    ventura:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.controlcenter:
    Bluetooth: 18
