id: system_settings_sleep_enforce
title: Enforce Display Sleep (Apple Silicon)
discussion: |
  Display Sleep _MUST_ be enforced on Apple Silicon MacBooks.
references:
  nist:
    cce:
      sonoma:
        - CCE-93023-0
    800-53r5:
      - null
    800-171r3:
      - null
  disa:
    cci:
      - null
    srg:
      - null
    disa_stig:
      sonoma:
        - null
  cis:
    benchmark:
      sonoma:
        - 2.9.1.2 (level 2)
    controls_v8:
      - 4.1
platforms:
  macOS:
    sonoma:
      benchmarks:
        - cis_lvl2
    check: |
      error_count=0
      if /usr/sbin/ioreg -rd1 -c IOPlatformExpertDevice 2>&1 | /usr/bin/grep -q "MacBook"; then
        sleepMode=$(/usr/bin/pmset -b -g | /usr/bin/grep '^\s*sleep' 2>&1 | /usr/bin/awk '{print $2}')
        displaysleepMode=$(/usr/bin/pmset -b -g | /usr/bin/grep displaysleep 2>&1 | /usr/bin/awk '{print $2}')

        if [[ "$sleepMode" == "" ]] || [[ "$sleepMode" -gt 15 ]]; then
          ((error_count++))
        fi
        if [[ "$displaysleepMode" == "" ]] || [[ "$displaysleepMode" -gt 10 ]] || [[ "$displaysleepMode" -lt "$sleepMode" ]]; then
          ((error_count++))
        fi
      fi
      echo "$error_count"
    result:
      integer: 0
tags:
  - cisv8
  - arm64
mobileconfig_info: null
