id: system_settings_wallet_applepay_settings_disable
title: Disable the System Settings Pane for Wallet and Apple Pay
discussion: |
  The System Settings pane for Wallet and Apple Pay _MUST_ be disabled.

  Disabling the System Settings pane prevents the users from configuring Wallet and Apple Pay.
references:
  nist:
    cce:
      macos_15:
        - CCE-94411-6
      macos_14:
        - CCE-93021-4
    800-53r5:
      - CM-7
      - CM-7(1)
      - CM-7(5)
    800-171r3:
      - 03.04.06
      - 03.04.08
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      macos_15:
        - APPL-15-002052
      macos_14:
        - APPL-14-002052
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: |
      /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledSystemSettings"]/following-sibling::*[1]' - | /usr/bin/grep -c "com.apple.WalletSettingsExtension"
    result:
      integer: 1
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      severity: medium
      benchmarks:
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - disa_stig
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cmmc_lvl2
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
mobileconfig_info:
  com.apple.systempreferences:
    DisabledSystemSettings:
      - com.apple.WalletSettingsExtension
