id: system_settings_wifi_menu_enable
title: "Enable Wifi Menu"
discussion: |
  The WiFi menu _MUST_ be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
  .objectForKey('WiFi').js
  EOS
result:
  integer: 18
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-93010-7
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 2.4.1 (level 1)
    controls v8:
      - 4.8
      - 12.6
macOS:
  - "14.0"
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.controlcenter:
    WiFi: 18