id: system_settings_automatic_login_disable
title: Disable Unattended or Automatic Logon to the System
discussion: |
  Automatic logon _MUST_ be disabled.

  When automatic logons are enabled, the default user account is automatically logged on at boot time without prompting the user for a password. Even if the screen is later locked, a malicious user would be able to reboot the computer and find it already logged in. Disabling automatic logons mitigates this risk.
references:
  nist:
    cce:
      macos_15:
        - CCE-94350-6
      macos_14:
        - CCE-92947-1
      macos_13:
        - CCE-91934-0
    800-53r5:
      - IA-2
      - IA-5(13)
    800-171r3:
      - 03.05.01
  disa:
    cci:
      - CCI-000366
    srg:
      - SRG-OS-000480-GPOS-00229
      - SRG-OS-000104-GPOS-00051
      - SRG-OS-000480-GPOS-00228
    disa_stig:
      macos_15:
        - APPL-15-002066
      macos_14:
        - APPL-14-002066
      macos_13:
        - APPL-13-002066
    cmmc:
      - IA.L1-3.5.1
      - IA.L1-3.5.2
  cis:
    benchmark:
      macos_15:
        - 2.13.3 (level 1)
      macos_14:
        - 2.12.3 (level 1)
      macos_13:
        - 2.12.3 (level 1)
    controls_v8:
      - 4.7
platforms:
  macOS:
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '13.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    enforcement_info:
      check:
        shell: |-
          /usr/bin/osascript -l JavaScript << EOS
          $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
          .objectForKey('com.apple.login.mcx.DisableAutoLoginClient').js
          EOS
        result:
          string: 'true'
    introduced: '-1'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info:
  - PayloadType: com.apple.loginwindow
    PayloadContent:
      - com.apple.login.mcx.DisableAutoLoginClient: true
