id: system_settings_printer_sharing_disable
title: Disable Printer Sharing
discussion: |
  Printer Sharing _MUST_ be disabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94384-5
      macos_14:
        - CCE-92980-2
      macos_13:
        - CCE-91969-6
    800-53r5:
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      macos_15:
        - APPL-15-002240
      macos_14:
        - APPL-14-002240
    cmmc:
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_15:
        - 2.3.3.3 (level 1)
      macos_14:
        - 2.3.3.4 (level 1)
      macos_13:
        - 2.3.3.4 (level 1)
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '13.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    enforcement_info:
      check:
        shell: /usr/sbin/cupsctl | /usr/bin/grep -c "_share_printers=0"
        result:
          integer: 1
      fix:
        shell: |-
          /usr/sbin/cupsctl --no-share-printers
          /usr/bin/lpstat -p | awk '{print $2}'| /usr/bin/xargs -I{} lpadmin -p {} -o printer-is-shared=false
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
