id: system_settings_firewall_stealth_mode_enable
title: "Enable Firewall Stealth Mode"
discussion: |
  Firewall Stealth Mode _MUST_ be enabled.

  When stealth mode is enabled, the Mac will not respond to any probing requests, and only requests from authorized applications will still be authorized.

  [IMPORTANT]
  ====
  Enabling firewall stealth mode may prevent certain remote mechanisms used for maintenance and compliance scanning from properly functioning. Information System Security Officers (ISSOs) are advised to first fully weigh the potential risks posed to their organization before opting not to enable stealth mode.
  ====
check: |
  profile="$(/usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.security.firewall')\
  .objectForKey('EnableStealthMode').js
  EOS
  )"

  plist=$(/usr/bin/defaults read /Library/Preferences/com.apple.alf stealthenabled 2>/dev/null)

  if [[ "$profile" == "true" ]] && [[ $plist == 1 ]]; then
    echo "true"
  else
    echo "false"
  fi
result:
  string: "true"
fix: |
  [source,bash]
  ----
  /usr/bin/defaults write /Library/Preferences/com.apple.alf stealthenabled -int 1
  ----
references:
  cce:
    - CCE-92960-4
  cci:
    - CCI-000366
  800-53r5:
    - CM-7
    - CM-7(1)
    - SC-7(16)
    - SC-7
  800-53r4:
    - SC-7
    - CM-7
    - CM-7(1)
    - SC-7(16)
  srg:
    - SRG-OS-000480-GPOS-00232
  disa_stig:
    - N/A
  800-171r2:
    - 3.4.6
    - 3.13.1
    - 3.13.2
    - 3.13.5
  cis:
    benchmark:
      - 2.2.2 (level 1)
    controls v8:
      - 4.1
      - 4.5
      - 4.8
  cmmc:
    - CM.L2-3.4.6
    - CM.L2-3.4.7
    - SC.L1-3.13.1
macOS:
  - "14.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.security.firewall:
    EnableStealthMode: true
    EnableFirewall: true
