id: system_settings_apple_watch_unlock_disable
title: "Prevent Apple Watch from Terminating a Session Lock"
discussion: |
  Apple Watches are not an approved authenticator and their use _MUST_ be disabled.

  Disabling Apple watches is a necessary step to ensuring that the information system retains a session lock until the user reestablishes access using an authorized identification and authentication procedures.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowAutoUnlock').js
  EOS
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91933-2
  cci: 
    - N/A
  800-53r5:
    - AC-11
  800-53r4: 
    - AC-11
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.1.10
  cmmc:
    - AC.L2-3.1.10
macOS:
  - "13.0"
tags:
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-171 
  - cnssi-1253
  - cmmc_lvl3
  - cmmc_lvl2
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowAutoUnlock: false
