id: system_settings_siri_disable
title: Disable Siri
discussion: |
  Support for Siri is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities.
references:
  nist:
    cce:
      sequoia:
        - CCE-94391-0
      sonoma:
        - CCE-92987-7
      ventura:
        - CCE-91976-1
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
      - SC-7(10)
    800-171r3:
      - 03.01.20
      - 03.04.06
      - 03.04.08
  disa:
    cci:
      - CCI-000381
      - CCI-001774
    srg:
      - SRG-OS-000095-GPOS-00049
    disa_stig:
      sequoia:
        - APPL-15-002020
      sonoma:
        - APPL-14-002020
      ventura:
        - APPL-13-002020
    cmmc:
      - AC.L1-3.1.20
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      sequoia:
        - null
      sonoma:
        - null
      ventura:
        - null
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    check: $OS_VALUE
    result:
      string: 'false'
    fix: |
      This is implemented by a Configuration Profile.
    sequoia:
      severity: medium
      benchmarks:
        - disa_stig
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
        .objectForKey('allowAssistant').js
        EOS
      mobileconfig_info:
        com.apple.applicationaccess:
          allowAssistant: false
    sonoma:
      severity: medium
      benchmarks:
        - disa_stig
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
        .objectForKey('allowAssistant').js
        EOS
      mobileconfig_info:
        com.apple.applicationaccess:
          allowAssistant: false
    ventura:
      severity: medium
      benchmarks:
        - disa_stig
      check: |-
        /usr/bin/osascript -l JavaScript << EOS
        $.NSUserDefaults.alloc.initWithSuiteName('com.apple.ironwood.support')\
        .objectForKey('Ironwood Allowed').js
        EOS
      mobileconfig_info:
        com.apple.ironwood.support:
          Ironwood Allowed: false
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info: $OS_VALUE
