id: system_settings_filevault_enforce
title: Enforce FileVault
discussion: |
  FileVault _MUST_ be enforced.

  The information system implements cryptographic mechanisms to protect the confidentiality and integrity of information stored on digital media during transport outside of controlled areas.
references:
  nist:
    cce:
      macos_15:
        - CCE-94360-5
      macos_14:
        - CCE-92957-0
      macos_13:
        - CCE-91946-4
    800-53r5:
      - SC-28
      - SC-28(1)
    800-171r3:
      - 03.13.08
  disa:
    cci:
      - CCI-001199
      - CCI-002475
      - CCI-002476
    srg:
      - SRG-OS-000185-GPOS-00079
      - SRG-OS-000405-GPOS-00184
      - SRG-OS-000404-GPOS-00183
    disa_stig:
      macos_15:
        - APPL-15-005020
      macos_14:
        - APPL-14-005020
      macos_13:
        - APPL-13-005020
    cmmc:
      - SC.L2-3.13.16
  cis:
    benchmark:
      macos_15:
        - 2.6.6 (level 1)
      macos_14:
        - 2.6.6 (level 1)
      macos_13:
        - 2.6.5 (level 1)
    controls_v8:
      - 3.6
      - 3.11
platforms:
  macOS:
    check: |
      dontAllowDisable=$(/usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
      .objectForKey('dontAllowFDEDisable').js
      EOS
      )
      fileVault=$(/usr/bin/fdesetup status | /usr/bin/grep -c "FileVault is On.")
      if [[ "$dontAllowDisable" == "true" ]] && [[ "$fileVault" == 1 ]]; then
        echo "1"
      else
        echo "0"
      fi
    result:
      integer: 1
    fix: |
      NOTE: See the FileVault supplemental to implement this rule.
    '15.0':
      severity: high
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: high
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      severity: high
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.MCX:
    dontAllowFDEDisable: true
