id: audit_configure_capacity_notify
title: Configure Audit Capacity Warning
discussion: |
  The audit service _MUST_ be configured to notify the system administrator when the amount of free disk space remaining reaches an organization defined value.

  This rule ensures that the system administrator is notified in advance that action is required to free up more disk space for audit logs.
references:
  nist:
    cce:
      macos_15:
        - CCE-94105-4
      macos_14:
        - CCE-92705-3
      macos_13:
        - CCE-91705-4
    800-53r5:
      - AU-5(1)
  disa:
    cci:
      - CCI-000139
      - CCI-001855
    srg:
      - SRG-OS-000046-GPOS-00022
      - SRG-OS-000343-GPOS-00134
    disa_stig:
      macos_15:
        - APPL-15-001030
      macos_14:
        - APPL-14-001030
      macos_13:
        - APPL-13-001030
platforms:
  macOS:
    check: |
      /usr/bin/awk -F: '/^minfree/{print $2}' /etc/security/audit_control
    result:
      integer: $ODV
    fix: |
      [source,bash]
      ----
      /usr/bin/sed -i.bak 's/.*minfree.*/minfree:$ODV/' /etc/security/audit_control; /usr/sbin/audit -s
      ----
    '15.0':
      severity: low
      benchmarks:
        - disa_stig
    '14.0':
      severity: low
      benchmarks:
        - disa_stig
    '13.0':
      severity: low
      benchmarks:
        - disa_stig
odv:
  hint: Percentage of free space.
  recommended: 25
  stig: 25
tags:
  - 800-53r5_high
  - cnssi-1253_low
  - cnssi-1253_high
  - cnssi-1253_moderate
