id: audit_control_mode_configure
title: Configure Audit_Control Owner to Mode 440 or Less Permissive
discussion: |
  /etc/security/audit_control _MUST_ be configured so that it is readable only by the root user and group wheel.
references:
  nist:
    cce:
      macos_26:
        - CCE-95108-7
      macos_15:
        - CCE-94108-8
      macos_14:
        - CCE-92708-7
    800-53r5:
      - AU-9
    800-171r3:
      - 03.03.08
  disa:
    cci:
      - CCI-000162
      - CCI-000163
      - CCI-000164
      - CCI-000171
      - CCI-001493
      - CCI-001494
      - CCI-001495
    srg:
      - SRG-OS-000256-GPOS-00097
      - SRG-OS-000057-GPOS-00027
      - SRG-OS-000063-GPOS-00032
      - SRG-OS-000059-GPOS-00029
      - SRG-OS-000257-GPOS-00098
      - SRG-OS-000258-GPOS-00099
      - SRG-OS-000058-GPOS-00028
    disa_stig:
      macos_26:
        - APPL-26-001130
      macos_15:
        - APPL-15-001130
      macos_14:
        - APPL-14-001130
    cmmc:
      - AU.L2-3.3.8
  cis:
    benchmark:
      macos_26:
        - 3.5 (level 1)
      macos_15:
        - 3.5 (level 1)
      macos_14:
        - 3.5 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
        - name: disa_stig
          severity: medium
    enforcement_info:
      check:
        shell: /bin/ls -l /etc/security/audit_control | /usr/bin/awk '!/-r--[r-]-----|current|total/{print $1}' | /usr/bin/wc -l | /usr/bin/xargs
        result:
          integer: 0
      fix:
        shell: /bin/chmod 440 /etc/security/audit_control
tags:
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
