id: audit_flags_lo_configure
title: "Configure System to Audit All Log In and Log Out Events"
discussion: |
  The audit system _MUST_ be configured to record all attempts to log in and out of the system (lo). 

  Frequently, an attacker that successfully gains access to a system has only gained access to an account with limited privileges, such as a guest account or a service account. The attacker must attempt to change to another user account with normal or elevated privileges in order to proceed. Auditing both successful and unsuccessful attempts to switch to another user account (by way of monitoring login and logout events) mitigates this risk.

  The information system monitors login and logout events.
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '^lo'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*[^-]lo" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,lo/' /etc/security/audit_control; /usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-90868-1
  cci: 
    - CCI-000067
    - CCI-000172
  800-53r5:
    - AC-2(12)
    - AU-12
    - AC-17(1)
    - AU-2
    - MA-4(1)
  800-53r4:
    - AU-2  
    - AC-17(1)
    - AU-12
    - MA-4(1)
  srg:
    - SRG-OS-000032-GPOS-00013
    - SRG-OS-000462-GPOS-00206
  disa_stig:
    - APPL-12-001002
  800-171r2:
    - 3.1.12
    - 3.3.1
    - 3.3.2
macOS:
  - "12.0"
tags:
  - 800-53r5_privacy 
  - 800-53r4_low 
  - 800-53r4_moderate 
  - 800-53r4_high 
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-171 
  - cnssi-1253
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info: