id: audit_acls_folders_mode_configure
title: "Configure Audit Log Folders to Mode 700 or Less Permissive"
discussion: |
  The audit service must be configured to create log folders with the correct permissions to prevent normal users from reading audit logs. Audit logs contain sensitive data about the system and users. If log folders are set to be readable and writable only by root or administrative users with sudo, the risk is mitigated.

  The audit log folder must only allow read, write, and execute by Root.
check: |
  /usr/bin/stat -f %A $(/usr/bin/grep '^dir' /etc/security/audit_control | awk -F: '{print $2}')
result:
  integer: 700
fix: |
  [source,bash]
  ----
  /bin/chmod 700 $(/usr/bin/grep '^dir' /etc/security/audit_control | awk -F: '{print $2}')
  ----
references:
  cce:
    - CCE-84705-3
  cci: 
    - CCI-000162
    - CCI-000163
    - CCI-000164
  800-53r4: 
    - AU-9
  srg: 
    - SRG-OS-000058-GPOS-00028
    - SRG-OS-000059-GPOS-00029
    - SRG-OS-000057-GPOS-00027
  disa_stig: 
    - AOSX-14-001017
macOS:
  - "10.15"
tags:
  - cnssi-1253
  - fisma-low
  - fisma-moderate
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info: