id: audit_flags_fd_configure
title: "Configure System to Audit All Deletions of Object Attributes"
discussion: |
  The audit system _MUST_ be configured to record enforcement actions of attempts to delete file attributes (fd). 

  ***Enforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). 
  
  This configuration ensures that audit lists include events in which enforcement actions prevent attempts to delete a file. 

  Without auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fd'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-fd" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fd/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-91719-5
  cci:
    - N/A
  800-53r5:
    - AC-2(12)
    - AU-12
    - AU-2
    - AU-9
    - CM-5(1)
    - MA-4(1)
  800-53r4: 
    - AU-2  
    - AU-12
    - AU-9
    - CM-5(1)
    - MA-4(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
macOS:
  - "13.0"
tags:
  - 800-53r5_privacy 
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
severity: "medium"
mobileconfig: false
mobileconfig_info: