id: audit_configure_capacity_notify
title: "Configure Audit Capacity Warning"
discussion: |
  The audit service _MUST_ be configured to notify the system administrator when the amount of free disk space remaining reaches an organization defined value. 

  This rule ensures that the system administrator is notified in advance that action is required to free up more disk space for audit logs.
check: |
  /usr/bin/grep -c "^minfree:25" /etc/security/audit_control
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/.*minfree.*/minfree:25/' /etc/security/audit_control; /usr/sbin/audit -s 
  ----
references:
  cce:
    - CCE-84707-9
  cci:
    - CCI-001855
  800-53r4: 
    - AU-5(1)
  srg: 
    - SRG-OS-000343-GPOS-00134
  disa_stig: 
    - AOSX-15-001030
macOS:
  - "10.15"
tags:
  - 800-53r4_high
mobileconfig: false
mobileconfig_info: