id: audit_flags_fm_configure
title: "Configure System to Audit All Change of Object Attributes"
discussion: |
  The audit system _MUST_ be configured to record enforcement actions of attempts to modify file attributes (fm). 

  Enforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). 
  
  This configuration ensures that audit lists include events in which enforcement actions prevent attempts to modify a file. 

  Without auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.
check: |
  /usr/bin/grep -Ec "^flags.*fm" /etc/security/audit_control
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak '/^flags/ s/$/,fm/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-84715-2
  cci:
    - CCI-000162
  800-53r4: 
    - AU-12(c)
    - AU-9
    - CM-5(1)
  srg: 
    - SRG-OS-000365-GPOS-00152
    - SRG-OS-000458-GPOS-00203
    - SRG-OS-000461-GPOS-00205
    - SRG-OS-000463-GPOS-00207
    - SRG-OS-000465-GPOS-00209
    - SRG-OS-000466-GPOS-00210
    - SRG-OS-000467-GPOS-00211
    - SRG-OS-000468-GPOS-00212
    - SRG-OS-000474-GPOS-00219
    - SRG-OS-000057-GPOS-00027
  disa_stig: 
    - AOSX-14-001016
macOS:
  - "10.15"
tags:
  - cnssi-1253
  - fisma-low
  - fisma-moderate
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info: