id: audit_flags_fm_configure
title: "Configure System to Audit All Changes of Object Attributes"
discussion: |
  The audit system _MUST_ be configured to record enforcement actions of attempts to modify file attributes (fm). 

  Enforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., modifications to a file by applying file permissions). 
  
  This configuration ensures that audit lists include events in which enforcement actions attempts to modify a file. 

  Without auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\fm'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,fm/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  cce:
    - CCE-91086-9
  cci:
    - CCI-000172
    - CCI-001814
  800-53r5:
    - AC-2(12)
    - AU-12
    - AU-2
    - AU-9
    - CM-5(1)
    - MA-4(1)
  800-53r4: 
    - AU-2  
    - AU-12
    - AU-9
    - CM-5(1)
    - MA-4(1)
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis_lvl1:
    - N/A
  cis_lvl2:
    - 3.2
  cisv8:
    - 3.14
    - 8.2
    - 8.5
macOS:
  - "12.0"
tags:
  - stig
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info: