id: audit_retention_configure
title: Configure Audit Retention to $ODV
discussion: |
  The audit service _MUST_ be configured to require records be kept for a organizational defined value before deletion, unless the system uses a central audit record storage facility.

  When "expire-after" is set to "$ODV", the audit service will not delete audit logs until the log data criteria is met.
references:
  nist:
    cce:
      macos_15:
        - CCE-94130-2
      macos_14:
        - CCE-92730-1
      macos_13:
        - CCE-91731-0
      monterey:
        - CCE-90875-6
      big_sur:
        - CCE-85272-3
      catalina:
        - CCE-84719-4
    800-53r5:
      - AU-11
      - AU-4
    800-171r3:
      - 03.03.03
  disa:
    cci:
      - CCI-001849
    srg:
      - SRG-OS-000341-GPOS-00132
    disa_stig:
      macos_15:
        - APPL-15-001029
      macos_14:
        - APPL-14-001029
      macos_13:
        - APPL-13-001029
      monterey:
        - APPL-12-001029
      big_sur:
        - APPL-11-001029
      catalina:
        - AOSX-15-001029
    cmmc:
      - AU.L2-3.3.1
  cis:
    benchmark:
      macos_15:
        - 3.4 (level 1)
      macos_14:
        - 3.4 (level 1)
      macos_13:
        - 3.4 (level 1)
      monterey:
        - 3.4 (level 1)
      big_sur:
        - 3.4 (level 1)
    controls_v8:
      - 8.1
      - 8.3
platforms:
  macOS:
    check: |
      /usr/bin/awk -F: '/expire-after/{print $2}' /etc/security/audit_control
    result:
      string: $ODV
    fix: |
      [source,bash]
      ----
      /usr/bin/sed -i.bak 's/^expire-after.*/expire-after:$ODV/' /etc/security/audit_control; /usr/sbin/audit -s
      ----
    '15.0':
      severity: low
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: low
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      severity: low
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    monterey:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    big_sur:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    catalina:
      severity: medium
      benchmarks:
        - disa_stig
odv:
  hint: See man audit_control for possible values.
  recommended: 7d
  cis_lvl1: 60d OR 1G
  cis_lvl2: 60d OR 1G
  stig: 7d
tags:
  - 800-171
  - 800-53r5_privacy
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
  - cnssi-1253
