id: audit_acls_files_configure
title: "Configure Audit Log Files to Not Contain ACLs"
discussion: |
  The audit log files _MUST_ not contain access control lists (ACLs).
  
  This rule ensures that audit information and audit files are configured to be readable and writable only by system administrators, thereby preventing unauthorized access, modification, and deletion of files.
check: |
  /bin/ls -le $(/usr/bin/awk -F: '/^dir/{print $2}' /etc/security/audit_control) | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
result: 
  integer: 0
fix: |
  [source,bash]
  ----
  /bin/chmod -RN $(/usr/bin/awk -F: '/^dir/{print $2}' /etc/security/audit_control)
  ----
references:
  cce:
    - CCE-84701-2
  cci:
    - CCI-000162
    - CCI-001314
  800-53r4:
    - AU-9
    - SI-11
  srg:
    - SRG-OS-000057-GPOS-00027
    - SRG-OS-000206-GPOS-00084
  disa_stig:
    - AOSX-14-000030
macOS:
  - "10.15"
tags:
  - cnssi-1253
  - fisma-low
  - fisma-moderate
  - fisma-high
  - STIG
mobileconfig: false
mobileconfig_info:
