id: audit_acls_folders_configure
title: "Configure Audit Log Folder to Not Contain Access Control Lists"
discussion: |
  The audit log folder _MUST_ not contain access control lists (ACLs).

  Audit logs contain sensitive data about the system and users. This rule ensures that the audit service is configured to create log folders that are readable and writable only by system administrators in order to prevent normal users from reading audit logs.
check: |
  /bin/ls -lde $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /bin/chmod -N $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
  ----
references:
  cce:
    - CCE-84704-6
  cci:
    - CCI-000162
    - CCI-001314
  800-53r4:
    - AU-9
    - SI-11
  srg:
    - SRG-OS-000057-GPOS-00027
    - SRG-OS-000206-GPOS-00084
  disa_stig:
    - AOSX-15-000030
  800-171r2:
    - 3.3.8
macOS:
  - "10.15"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
mobileconfig: false
mobileconfig_info: